2016/06/22 07:42:47 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[HY000] [1049] Unknown database 'testdrive'' in C:\xampp\htdocs\prestamo\framework\db\CDbConnection.php:399
Stack trace:
#0 C:\xampp\htdocs\prestamo\framework\db\CDbConnection.php(347): CDbConnection->open()
#1 C:\xampp\htdocs\prestamo\framework\db\CDbConnection.php(325): CDbConnection->setActive(true)
#2 C:\xampp\htdocs\prestamo\framework\base\CModule.php(394): CDbConnection->init()
#3 C:\xampp\htdocs\prestamo\framework\base\CModule.php(103): CModule->getComponent('db')
#4 C:\xampp\htdocs\prestamo\framework\gii\generators\model\ModelCode.php(60): CModule->__get('db')
#5 C:\xampp\htdocs\prestamo\framework\web\CFormModel.php(39): ModelCode->init()
#6 C:\xampp\htdocs\prestamo\framework\gii\CCodeGenerator.php(153): CFormModel->__construct()
#7 C:\xampp\htdocs\prestamo\framework\gii\CCodeGenerator.php(63): CCodeGenerator->prepare()
#8 C:\xampp\htdocs\prestamo\framework\web\actions\CInlineAction.php(49): CCodeGenerator->actionIndex()
#9 C:\xampp\htdocs\prestamo\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#10 C:\xampp\htdocs\prestamo\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#11 C:\xampp\htdocs\prestamo\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 C:\xampp\htdocs\prestamo\framework\web\CWebApplication.php(282): CController->run('index')
#13 C:\xampp\htdocs\prestamo\framework\web\CWebApplication.php(141): CWebApplication->runController('gii/model/index')
#14 C:\xampp\htdocs\prestamo\framework\base\CApplication.php(185): CWebApplication->processRequest()
#15 C:\xampp\htdocs\prestamo\prestamo\index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/prestamo/prestamo/index.php?r=gii/model/index
HTTP_REFERER=http://localhost:8080/prestamo/prestamo/index.php?r=gii/model/index
---
2016/06/22 07:42:53 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[HY000] [1049] Unknown database 'testdrive'' in C:\xampp\htdocs\prestamo\framework\db\CDbConnection.php:399
Stack trace:
#0 C:\xampp\htdocs\prestamo\framework\db\CDbConnection.php(347): CDbConnection->open()
#1 C:\xampp\htdocs\prestamo\framework\db\CDbConnection.php(325): CDbConnection->setActive(true)
#2 C:\xampp\htdocs\prestamo\framework\base\CModule.php(394): CDbConnection->init()
#3 C:\xampp\htdocs\prestamo\framework\base\CModule.php(103): CModule->getComponent('db')
#4 C:\xampp\htdocs\prestamo\framework\gii\generators\model\ModelCode.php(60): CModule->__get('db')
#5 C:\xampp\htdocs\prestamo\framework\web\CFormModel.php(39): ModelCode->init()
#6 C:\xampp\htdocs\prestamo\framework\gii\CCodeGenerator.php(153): CFormModel->__construct()
#7 C:\xampp\htdocs\prestamo\framework\gii\CCodeGenerator.php(63): CCodeGenerator->prepare()
#8 C:\xampp\htdocs\prestamo\framework\web\actions\CInlineAction.php(49): CCodeGenerator->actionIndex()
#9 C:\xampp\htdocs\prestamo\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#10 C:\xampp\htdocs\prestamo\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#11 C:\xampp\htdocs\prestamo\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 C:\xampp\htdocs\prestamo\framework\web\CWebApplication.php(282): CController->run('index')
#13 C:\xampp\htdocs\prestamo\framework\web\CWebApplication.php(141): CWebApplication->runController('gii/model/index')
#14 C:\xampp\htdocs\prestamo\framework\base\CApplication.php(185): CWebApplication->processRequest()
#15 C:\xampp\htdocs\prestamo\prestamo\index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/prestamo/prestamo/index.php?r=gii/model/index
HTTP_REFERER=http://localhost:8080/prestamo/prestamo/index.php?r=gii/module/index
---
2016/06/22 07:44:27 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[HY000] [1049] Unknown database 'testdrive'' in C:\xampp\htdocs\prestamo\framework\db\CDbConnection.php:399
Stack trace:
#0 C:\xampp\htdocs\prestamo\framework\db\CDbConnection.php(347): CDbConnection->open()
#1 C:\xampp\htdocs\prestamo\framework\db\CDbConnection.php(325): CDbConnection->setActive(true)
#2 C:\xampp\htdocs\prestamo\framework\base\CModule.php(394): CDbConnection->init()
#3 C:\xampp\htdocs\prestamo\framework\base\CModule.php(103): CModule->getComponent('db')
#4 C:\xampp\htdocs\prestamo\framework\gii\generators\model\ModelCode.php(60): CModule->__get('db')
#5 C:\xampp\htdocs\prestamo\framework\web\CFormModel.php(39): ModelCode->init()
#6 C:\xampp\htdocs\prestamo\framework\gii\CCodeGenerator.php(153): CFormModel->__construct()
#7 C:\xampp\htdocs\prestamo\framework\gii\CCodeGenerator.php(63): CCodeGenerator->prepare()
#8 C:\xampp\htdocs\prestamo\framework\web\actions\CInlineAction.php(49): CCodeGenerator->actionIndex()
#9 C:\xampp\htdocs\prestamo\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#10 C:\xampp\htdocs\prestamo\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#11 C:\xampp\htdocs\prestamo\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 C:\xampp\htdocs\prestamo\framework\web\CWebApplication.php(282): CController->run('index')
#13 C:\xampp\htdocs\prestamo\framework\web\CWebApplication.php(141): CWebApplication->runController('gii/model/index')
#14 C:\xampp\htdocs\prestamo\framework\base\CApplication.php(185): CWebApplication->processRequest()
#15 C:\xampp\htdocs\prestamo\prestamo\index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/prestamo/prestamo/index.php?r=gii/model/index
HTTP_REFERER=http://localhost:8080/prestamo/prestamo/index.php?r=gii/module/index
---
2016/06/22 07:44:32 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[HY000] [1049] Unknown database 'testdrive'' in C:\xampp\htdocs\prestamo\framework\db\CDbConnection.php:399
Stack trace:
#0 C:\xampp\htdocs\prestamo\framework\db\CDbConnection.php(347): CDbConnection->open()
#1 C:\xampp\htdocs\prestamo\framework\db\CDbConnection.php(325): CDbConnection->setActive(true)
#2 C:\xampp\htdocs\prestamo\framework\base\CModule.php(394): CDbConnection->init()
#3 C:\xampp\htdocs\prestamo\framework\base\CModule.php(103): CModule->getComponent('db')
#4 C:\xampp\htdocs\prestamo\framework\gii\generators\model\ModelCode.php(60): CModule->__get('db')
#5 C:\xampp\htdocs\prestamo\framework\web\CFormModel.php(39): ModelCode->init()
#6 C:\xampp\htdocs\prestamo\framework\gii\CCodeGenerator.php(153): CFormModel->__construct()
#7 C:\xampp\htdocs\prestamo\framework\gii\CCodeGenerator.php(63): CCodeGenerator->prepare()
#8 C:\xampp\htdocs\prestamo\framework\web\actions\CInlineAction.php(49): CCodeGenerator->actionIndex()
#9 C:\xampp\htdocs\prestamo\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#10 C:\xampp\htdocs\prestamo\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#11 C:\xampp\htdocs\prestamo\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 C:\xampp\htdocs\prestamo\framework\web\CWebApplication.php(282): CController->run('index')
#13 C:\xampp\htdocs\prestamo\framework\web\CWebApplication.php(141): CWebApplication->runController('gii/model/index')
#14 C:\xampp\htdocs\prestamo\framework\base\CApplication.php(185): CWebApplication->processRequest()
#15 C:\xampp\htdocs\prestamo\prestamo\index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/prestamo/prestamo/index.php?r=gii/model/index
HTTP_REFERER=http://localhost:8080/prestamo/prestamo/index.php?r=gii
---
2016/06/22 07:44:51 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[HY000] [1049] Unknown database 'testdrive'' in C:\xampp\htdocs\prestamo\framework\db\CDbConnection.php:399
Stack trace:
#0 C:\xampp\htdocs\prestamo\framework\db\CDbConnection.php(347): CDbConnection->open()
#1 C:\xampp\htdocs\prestamo\framework\db\CDbConnection.php(325): CDbConnection->setActive(true)
#2 C:\xampp\htdocs\prestamo\framework\base\CModule.php(394): CDbConnection->init()
#3 C:\xampp\htdocs\prestamo\framework\base\CModule.php(103): CModule->getComponent('db')
#4 C:\xampp\htdocs\prestamo\framework\gii\generators\crud\CrudCode.php(44): CModule->__get('db')
#5 C:\xampp\htdocs\prestamo\framework\web\CFormModel.php(39): CrudCode->init()
#6 C:\xampp\htdocs\prestamo\framework\gii\CCodeGenerator.php(153): CFormModel->__construct()
#7 C:\xampp\htdocs\prestamo\framework\gii\CCodeGenerator.php(63): CCodeGenerator->prepare()
#8 C:\xampp\htdocs\prestamo\framework\web\actions\CInlineAction.php(49): CCodeGenerator->actionIndex()
#9 C:\xampp\htdocs\prestamo\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#10 C:\xampp\htdocs\prestamo\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#11 C:\xampp\htdocs\prestamo\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 C:\xampp\htdocs\prestamo\framework\web\CWebApplication.php(282): CController->run('index')
#13 C:\xampp\htdocs\prestamo\framework\web\CWebApplication.php(141): CWebApplication->runController('gii/crud/index')
#14 C:\xampp\htdocs\prestamo\framework\base\CApplication.php(185): CWebApplication->processRequest()
#15 C:\xampp\htdocs\prestamo\prestamo\index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/prestamo/prestamo/index.php?r=gii/crud/index
HTTP_REFERER=http://localhost:8080/prestamo/prestamo/index.php?r=gii/form/index
---
2016/06/22 07:57:03 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "Cliente.html".' in C:\xampp\htdocs\prestamo\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\prestamo\framework\web\CController.php(270): CController->missingAction('Cliente.html')
#1 C:\xampp\htdocs\prestamo\framework\web\CWebApplication.php(282): CController->run('Cliente.html')
#2 C:\xampp\htdocs\prestamo\framework\web\CWebApplication.php(141): CWebApplication->runController('site/Cliente.ht...')
#3 C:\xampp\htdocs\prestamo\framework\base\CApplication.php(185): CWebApplication->processRequest()
#4 C:\xampp\htdocs\prestamo\prestamo\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/prestamo/prestamo/index.php?r=site/Cliente.html
---
2016/06/22 08:23:35 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "admin.php".' in C:\xampp\htdocs\prestamo\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\prestamo\framework\web\CController.php(270): CController->missingAction('admin.php')
#1 C:\xampp\htdocs\prestamo\framework\web\CWebApplication.php(282): CController->run('admin.php')
#2 C:\xampp\htdocs\prestamo\framework\web\CWebApplication.php(141): CWebApplication->runController('credito/admin.p...')
#3 C:\xampp\htdocs\prestamo\framework\base\CApplication.php(185): CWebApplication->processRequest()
#4 C:\xampp\htdocs\prestamo\prestamo\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/prestamo/prestamo/index.php?r=credito/admin.php
HTTP_REFERER=http://localhost:8080/prestamo/prestamo/index.php?r=site/login
---
2016/06/22 08:24:29 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "admin.php".' in C:\xampp\htdocs\prestamo\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\prestamo\framework\web\CController.php(270): CController->missingAction('admin.php')
#1 C:\xampp\htdocs\prestamo\framework\web\CWebApplication.php(282): CController->run('admin.php')
#2 C:\xampp\htdocs\prestamo\framework\web\CWebApplication.php(141): CWebApplication->runController('credito/admin.p...')
#3 C:\xampp\htdocs\prestamo\framework\base\CApplication.php(185): CWebApplication->processRequest()
#4 C:\xampp\htdocs\prestamo\prestamo\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/prestamo/prestamo/index.php?r=credito/admin.php
HTTP_REFERER=http://localhost:8080/prestamo/prestamo/index.php?r=site/login
---
2016/06/22 08:24:57 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "admin.php".' in C:\xampp\htdocs\prestamo\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\prestamo\framework\web\CController.php(270): CController->missingAction('admin.php')
#1 C:\xampp\htdocs\prestamo\framework\web\CWebApplication.php(282): CController->run('admin.php')
#2 C:\xampp\htdocs\prestamo\framework\web\CWebApplication.php(141): CWebApplication->runController('credito/admin.p...')
#3 C:\xampp\htdocs\prestamo\framework\base\CApplication.php(185): CWebApplication->processRequest()
#4 C:\xampp\htdocs\prestamo\prestamo\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/prestamo/prestamo/index.php?r=credito/admin.php
HTTP_REFERER=http://localhost:8080/prestamo/prestamo/index.php?r=site/login
---
2016/06/22 08:50:18 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "submenu/sub0".' in C:\xampp\htdocs\prestamo\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\prestamo\framework\web\CWebApplication.php(141): CWebApplication->runController('submenu/sub0')
#1 C:\xampp\htdocs\prestamo\framework\base\CApplication.php(185): CWebApplication->processRequest()
#2 C:\xampp\htdocs\prestamo\prestamo\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/prestamo/prestamo/index.php?r=submenu/sub0
HTTP_REFERER=http://localhost:8080/prestamo/prestamo/index.php?r=cliente/create
---
2016/06/22 08:50:29 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "submenu/sub0".' in C:\xampp\htdocs\prestamo\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\prestamo\framework\web\CWebApplication.php(141): CWebApplication->runController('submenu/sub0')
#1 C:\xampp\htdocs\prestamo\framework\base\CApplication.php(185): CWebApplication->processRequest()
#2 C:\xampp\htdocs\prestamo\prestamo\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/prestamo/prestamo/index.php?r=submenu/sub0
HTTP_REFERER=http://localhost:8080/prestamo/prestamo/index.php?r=credito/admin
---
2016/06/22 08:51:03 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "submenu/sub0".' in C:\xampp\htdocs\prestamo\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\prestamo\framework\web\CWebApplication.php(141): CWebApplication->runController('submenu/sub0')
#1 C:\xampp\htdocs\prestamo\framework\base\CApplication.php(185): CWebApplication->processRequest()
#2 C:\xampp\htdocs\prestamo\prestamo\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/prestamo/prestamo/index.php?r=submenu/sub0
HTTP_REFERER=http://localhost:8080/prestamo/prestamo/index.php?r=credito/admin
---
2016/06/22 08:51:13 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "submenu/sub1".' in C:\xampp\htdocs\prestamo\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\prestamo\framework\web\CWebApplication.php(141): CWebApplication->runController('submenu/sub1')
#1 C:\xampp\htdocs\prestamo\framework\base\CApplication.php(185): CWebApplication->processRequest()
#2 C:\xampp\htdocs\prestamo\prestamo\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/prestamo/prestamo/index.php?r=submenu/sub1
HTTP_REFERER=http://localhost:8080/prestamo/prestamo/
---
2016/06/22 09:05:30 [error] [exception.CException] exception 'CException' with message 'Alias "zii.widgets.mbmenu" is invalid. Make sure it points to an existing PHP file and the file is readable.' in C:\xampp\htdocs\prestamo\framework\YiiBase.php:323
Stack trace:
#0 C:\xampp\htdocs\prestamo\framework\web\CWidgetFactory.php(146): YiiBase::import('zii.widgets.mbm...', true)
#1 C:\xampp\htdocs\prestamo\framework\web\CBaseController.php(146): CWidgetFactory->createWidget(Object(SiteController), 'zii.widgets.mbm...', Array)
#2 C:\xampp\htdocs\prestamo\framework\web\CBaseController.php(180): CBaseController->createWidget('zii.widgets.mbm...', Array)
#3 C:\xampp\htdocs\prestamo\prestamo\protected\views\layouts\main.php(52): CBaseController->widget('zii.widgets.mbm...', Array)
#4 C:\xampp\htdocs\prestamo\framework\web\CBaseController.php(126): require('C:\\xampp\\htdocs...')
#5 C:\xampp\htdocs\prestamo\framework\web\CBaseController.php(95): CBaseController->renderInternal('C:\\xampp\\htdocs...', Array, true)
#6 C:\xampp\htdocs\prestamo\framework\web\widgets\CContentDecorator.php(76): CBaseController->renderFile('C:\\xampp\\htdocs...', Array, true)
#7 C:\xampp\htdocs\prestamo\framework\web\widgets\CContentDecorator.php(54): CContentDecorator->decorate('<div id="conten...')
#8 C:\xampp\htdocs\prestamo\framework\web\widgets\COutputProcessor.php(44): CContentDecorator->processOutput('<div id="conten...')
#9 C:\xampp\htdocs\prestamo\framework\web\CBaseController.php(214): COutputProcessor->run()
#10 C:\xampp\htdocs\prestamo\framework\web\CBaseController.php(308): CBaseController->endWidget('CContentDecorat...')
#11 C:\xampp\htdocs\prestamo\prestamo\protected\views\layouts\column1.php(6): CBaseController->endContent()
#12 C:\xampp\htdocs\prestamo\framework\web\CBaseController.php(126): require('C:\\xampp\\htdocs...')
#13 C:\xampp\htdocs\prestamo\framework\web\CBaseController.php(95): CBaseController->renderInternal('C:\\xampp\\htdocs...', Array, true)
#14 C:\xampp\htdocs\prestamo\framework\web\CController.php(784): CBaseController->renderFile('C:\\xampp\\htdocs...', Array, true)
#15 C:\xampp\htdocs\prestamo\prestamo\protected\controllers\SiteController.php(32): CController->render('index')
#16 C:\xampp\htdocs\prestamo\framework\web\actions\CInlineAction.php(49): SiteController->actionIndex()
#17 C:\xampp\htdocs\prestamo\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#18 C:\xampp\htdocs\prestamo\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#19 C:\xampp\htdocs\prestamo\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#20 C:\xampp\htdocs\prestamo\framework\web\CWebApplication.php(282): CController->run('')
#21 C:\xampp\htdocs\prestamo\framework\web\CWebApplication.php(141): CWebApplication->runController('')
#22 C:\xampp\htdocs\prestamo\framework\base\CApplication.php(185): CWebApplication->processRequest()
#23 C:\xampp\htdocs\prestamo\prestamo\index.php(13): CApplication->run()
#24 {main}
REQUEST_URI=/prestamo/prestamo/
---
2016/06/22 09:05:49 [error] [exception.CException] exception 'CException' with message 'Alias "zii.widgets.mbmenu.mbmenu" is invalid. Make sure it points to an existing PHP file and the file is readable.' in C:\xampp\htdocs\prestamo\framework\YiiBase.php:323
Stack trace:
#0 C:\xampp\htdocs\prestamo\framework\web\CWidgetFactory.php(146): YiiBase::import('zii.widgets.mbm...', true)
#1 C:\xampp\htdocs\prestamo\framework\web\CBaseController.php(146): CWidgetFactory->createWidget(Object(SiteController), 'zii.widgets.mbm...', Array)
#2 C:\xampp\htdocs\prestamo\framework\web\CBaseController.php(180): CBaseController->createWidget('zii.widgets.mbm...', Array)
#3 C:\xampp\htdocs\prestamo\prestamo\protected\views\layouts\main.php(52): CBaseController->widget('zii.widgets.mbm...', Array)
#4 C:\xampp\htdocs\prestamo\framework\web\CBaseController.php(126): require('C:\\xampp\\htdocs...')
#5 C:\xampp\htdocs\prestamo\framework\web\CBaseController.php(95): CBaseController->renderInternal('C:\\xampp\\htdocs...', Array, true)
#6 C:\xampp\htdocs\prestamo\framework\web\widgets\CContentDecorator.php(76): CBaseController->renderFile('C:\\xampp\\htdocs...', Array, true)
#7 C:\xampp\htdocs\prestamo\framework\web\widgets\CContentDecorator.php(54): CContentDecorator->decorate('<div id="conten...')
#8 C:\xampp\htdocs\prestamo\framework\web\widgets\COutputProcessor.php(44): CContentDecorator->processOutput('<div id="conten...')
#9 C:\xampp\htdocs\prestamo\framework\web\CBaseController.php(214): COutputProcessor->run()
#10 C:\xampp\htdocs\prestamo\framework\web\CBaseController.php(308): CBaseController->endWidget('CContentDecorat...')
#11 C:\xampp\htdocs\prestamo\prestamo\protected\views\layouts\column1.php(6): CBaseController->endContent()
#12 C:\xampp\htdocs\prestamo\framework\web\CBaseController.php(126): require('C:\\xampp\\htdocs...')
#13 C:\xampp\htdocs\prestamo\framework\web\CBaseController.php(95): CBaseController->renderInternal('C:\\xampp\\htdocs...', Array, true)
#14 C:\xampp\htdocs\prestamo\framework\web\CController.php(784): CBaseController->renderFile('C:\\xampp\\htdocs...', Array, true)
#15 C:\xampp\htdocs\prestamo\prestamo\protected\controllers\SiteController.php(32): CController->render('index')
#16 C:\xampp\htdocs\prestamo\framework\web\actions\CInlineAction.php(49): SiteController->actionIndex()
#17 C:\xampp\htdocs\prestamo\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#18 C:\xampp\htdocs\prestamo\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#19 C:\xampp\htdocs\prestamo\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#20 C:\xampp\htdocs\prestamo\framework\web\CWebApplication.php(282): CController->run('')
#21 C:\xampp\htdocs\prestamo\framework\web\CWebApplication.php(141): CWebApplication->runController('')
#22 C:\xampp\htdocs\prestamo\framework\base\CApplication.php(185): CWebApplication->processRequest()
#23 C:\xampp\htdocs\prestamo\prestamo\index.php(13): CApplication->run()
#24 {main}
REQUEST_URI=/prestamo/prestamo/
---
2016/06/22 09:08:11 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "submenu/sub0".' in C:\xampp\htdocs\prestamo\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\prestamo\framework\web\CWebApplication.php(141): CWebApplication->runController('submenu/sub0')
#1 C:\xampp\htdocs\prestamo\framework\base\CApplication.php(185): CWebApplication->processRequest()
#2 C:\xampp\htdocs\prestamo\prestamo\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/prestamo/prestamo/index.php?r=submenu/sub0
HTTP_REFERER=http://localhost:8080/prestamo/prestamo/index.php?r=credito/admin
---
2016/06/22 09:36:35 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "submenu/index".' in C:\xampp\htdocs\prestamo\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\prestamo\framework\web\CWebApplication.php(141): CWebApplication->runController('submenu/index')
#1 C:\xampp\htdocs\prestamo\framework\base\CApplication.php(185): CWebApplication->processRequest()
#2 C:\xampp\htdocs\prestamo\prestamo\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/prestamo/prestamo/index.php?r=submenu/index
HTTP_REFERER=http://localhost:8080/prestamo/prestamo/index.php?r=credito/admin
---
2016/06/22 09:36:41 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "main".' in C:\xampp\htdocs\prestamo\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\prestamo\framework\web\CController.php(270): CController->missingAction('main')
#1 C:\xampp\htdocs\prestamo\framework\web\CWebApplication.php(282): CController->run('main')
#2 C:\xampp\htdocs\prestamo\framework\web\CWebApplication.php(141): CWebApplication->runController('pago/main')
#3 C:\xampp\htdocs\prestamo\framework\base\CApplication.php(185): CWebApplication->processRequest()
#4 C:\xampp\htdocs\prestamo\prestamo\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/prestamo/prestamo/index.php?r=pago/main
HTTP_REFERER=http://localhost:8080/prestamo/prestamo/index.php?r=credito/admin
---
2016/06/22 09:37:07 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "submenu/index".' in C:\xampp\htdocs\prestamo\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\prestamo\framework\web\CWebApplication.php(141): CWebApplication->runController('submenu/index')
#1 C:\xampp\htdocs\prestamo\framework\base\CApplication.php(185): CWebApplication->processRequest()
#2 C:\xampp\htdocs\prestamo\prestamo\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/prestamo/prestamo/index.php?r=submenu/index
HTTP_REFERER=http://localhost:8080/prestamo/prestamo/index.php
---
2016/06/22 09:37:14 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "main".' in C:\xampp\htdocs\prestamo\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\prestamo\framework\web\CController.php(270): CController->missingAction('main')
#1 C:\xampp\htdocs\prestamo\framework\web\CWebApplication.php(282): CController->run('main')
#2 C:\xampp\htdocs\prestamo\framework\web\CWebApplication.php(141): CWebApplication->runController('credito/main')
#3 C:\xampp\htdocs\prestamo\framework\base\CApplication.php(185): CWebApplication->processRequest()
#4 C:\xampp\htdocs\prestamo\prestamo\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/prestamo/prestamo/index.php?r=credito/main
HTTP_REFERER=http://localhost:8080/prestamo/prestamo/index.php
---
2016/06/22 09:38:33 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "main".' in C:\xampp\htdocs\prestamo\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\prestamo\framework\web\CController.php(270): CController->missingAction('main')
#1 C:\xampp\htdocs\prestamo\framework\web\CWebApplication.php(282): CController->run('main')
#2 C:\xampp\htdocs\prestamo\framework\web\CWebApplication.php(141): CWebApplication->runController('credito/main')
#3 C:\xampp\htdocs\prestamo\framework\base\CApplication.php(185): CWebApplication->processRequest()
#4 C:\xampp\htdocs\prestamo\prestamo\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/prestamo/prestamo/index.php?r=credito/main
HTTP_REFERER=http://localhost:8080/prestamo/prestamo/index.php
---
2016/06/22 09:38:42 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "submenu/index".' in C:\xampp\htdocs\prestamo\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\prestamo\framework\web\CWebApplication.php(141): CWebApplication->runController('submenu/index')
#1 C:\xampp\htdocs\prestamo\framework\base\CApplication.php(185): CWebApplication->processRequest()
#2 C:\xampp\htdocs\prestamo\prestamo\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/prestamo/prestamo/index.php?r=submenu/index
HTTP_REFERER=http://localhost:8080/prestamo/prestamo/index.php?r=pago/admin
---
2016/06/22 09:56:32 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "submenu/index".' in C:\xampp\htdocs\prestamo\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\prestamo\framework\web\CWebApplication.php(141): CWebApplication->runController('submenu/index')
#1 C:\xampp\htdocs\prestamo\framework\base\CApplication.php(185): CWebApplication->processRequest()
#2 C:\xampp\htdocs\prestamo\prestamo\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/prestamo/prestamo/index.php?r=submenu/index
HTTP_REFERER=http://localhost:8080/prestamo/prestamo/index.php?r=site/index
---
2016/06/22 09:56:39 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "submenu/index".' in C:\xampp\htdocs\prestamo\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\prestamo\framework\web\CWebApplication.php(141): CWebApplication->runController('submenu/index')
#1 C:\xampp\htdocs\prestamo\framework\base\CApplication.php(185): CWebApplication->processRequest()
#2 C:\xampp\htdocs\prestamo\prestamo\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/prestamo/prestamo/index.php?r=submenu/index
HTTP_REFERER=http://localhost:8080/prestamo/prestamo/index.php?r=usuario/admin
---
2016/06/22 09:56:43 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "submenu/index".' in C:\xampp\htdocs\prestamo\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\prestamo\framework\web\CWebApplication.php(141): CWebApplication->runController('submenu/index')
#1 C:\xampp\htdocs\prestamo\framework\base\CApplication.php(185): CWebApplication->processRequest()
#2 C:\xampp\htdocs\prestamo\prestamo\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/prestamo/prestamo/index.php?r=submenu/index
HTTP_REFERER=http://localhost:8080/prestamo/prestamo/index.php?r=usuario/admin
---
2016/06/22 09:58:14 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "submenu/index".' in C:\xampp\htdocs\prestamo\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\prestamo\framework\web\CWebApplication.php(141): CWebApplication->runController('submenu/index')
#1 C:\xampp\htdocs\prestamo\framework\base\CApplication.php(185): CWebApplication->processRequest()
#2 C:\xampp\htdocs\prestamo\prestamo\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/prestamo/prestamo/index.php?r=submenu/index
HTTP_REFERER=http://localhost:8080/prestamo/prestamo/index.php?r=pago/admin
---
2016/06/22 12:06:36 [error] [exception.CException] exception 'CException' with message 'Property "SiteController.mens" is not defined.' in C:\xampp\htdocs\prestamo\framework\base\CComponent.php:130
Stack trace:
#0 C:\xampp\htdocs\prestamo\prestamo\protected\views\site\index.php(10): CComponent->__get('mens')
#1 C:\xampp\htdocs\prestamo\framework\web\CBaseController.php(126): require('C:\\xampp\\htdocs...')
#2 C:\xampp\htdocs\prestamo\framework\web\CBaseController.php(95): CBaseController->renderInternal('C:\\xampp\\htdocs...', NULL, true)
#3 C:\xampp\htdocs\prestamo\framework\web\CController.php(869): CBaseController->renderFile('C:\\xampp\\htdocs...', NULL, true)
#4 C:\xampp\htdocs\prestamo\framework\web\CController.php(782): CController->renderPartial('index', NULL, true)
#5 C:\xampp\htdocs\prestamo\prestamo\protected\controllers\SiteController.php(32): CController->render('index')
#6 C:\xampp\htdocs\prestamo\framework\web\actions\CInlineAction.php(49): SiteController->actionIndex()
#7 C:\xampp\htdocs\prestamo\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#8 C:\xampp\htdocs\prestamo\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#9 C:\xampp\htdocs\prestamo\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#10 C:\xampp\htdocs\prestamo\framework\web\CWebApplication.php(282): CController->run('index')
#11 C:\xampp\htdocs\prestamo\framework\web\CWebApplication.php(141): CWebApplication->runController('site/index')
#12 C:\xampp\htdocs\prestamo\framework\base\CApplication.php(185): CWebApplication->processRequest()
#13 C:\xampp\htdocs\prestamo\prestamo\index.php(13): CApplication->run()
#14 {main}
REQUEST_URI=/prestamo/prestamo/index.php?r=site/index
HTTP_REFERER=http://localhost:8080/prestamo/prestamo/index.php?r=site/contact
---
2016/06/22 12:06:57 [error] [exception.CException] exception 'CException' with message 'Property "SiteController.mens" is not defined.' in C:\xampp\htdocs\prestamo\framework\base\CComponent.php:130
Stack trace:
#0 C:\xampp\htdocs\prestamo\prestamo\protected\views\site\index.php(10): CComponent->__get('mens')
#1 C:\xampp\htdocs\prestamo\framework\web\CBaseController.php(126): require('C:\\xampp\\htdocs...')
#2 C:\xampp\htdocs\prestamo\framework\web\CBaseController.php(95): CBaseController->renderInternal('C:\\xampp\\htdocs...', NULL, true)
#3 C:\xampp\htdocs\prestamo\framework\web\CController.php(869): CBaseController->renderFile('C:\\xampp\\htdocs...', NULL, true)
#4 C:\xampp\htdocs\prestamo\framework\web\CController.php(782): CController->renderPartial('index', NULL, true)
#5 C:\xampp\htdocs\prestamo\prestamo\protected\controllers\SiteController.php(32): CController->render('index')
#6 C:\xampp\htdocs\prestamo\framework\web\actions\CInlineAction.php(49): SiteController->actionIndex()
#7 C:\xampp\htdocs\prestamo\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#8 C:\xampp\htdocs\prestamo\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#9 C:\xampp\htdocs\prestamo\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#10 C:\xampp\htdocs\prestamo\framework\web\CWebApplication.php(282): CController->run('index')
#11 C:\xampp\htdocs\prestamo\framework\web\CWebApplication.php(141): CWebApplication->runController('site/index')
#12 C:\xampp\htdocs\prestamo\framework\base\CApplication.php(185): CWebApplication->processRequest()
#13 C:\xampp\htdocs\prestamo\prestamo\index.php(13): CApplication->run()
#14 {main}
REQUEST_URI=/prestamo/prestamo/index.php?r=site/index
HTTP_REFERER=http://localhost:8080/prestamo/prestamo/index.php?r=site/contact
---
2016/06/22 14:04:30 [error] [php] mail(): Failed to connect to mailserver at &quot;localhost&quot; port 25, verify your &quot;SMTP&quot; and &quot;smtp_port&quot; setting in php.ini or use ini_set() (C:\xampp\htdocs\prestamo\prestamo\protected\controllers\SiteController.php:67)
Stack trace:
#0 C:\xampp\htdocs\prestamo\framework\web\CController.php(308): CInlineAction->runWithParams()
#1 C:\xampp\htdocs\prestamo\framework\web\CController.php(286): SiteController->runAction()
#2 C:\xampp\htdocs\prestamo\framework\web\CController.php(265): SiteController->runActionWithFilters()
#3 C:\xampp\htdocs\prestamo\framework\web\CWebApplication.php(282): SiteController->run()
#4 C:\xampp\htdocs\prestamo\framework\web\CWebApplication.php(141): CWebApplication->runController()
#5 C:\xampp\htdocs\prestamo\framework\base\CApplication.php(185): CWebApplication->processRequest()
#6 C:\xampp\htdocs\prestamo\prestamo\index.php(13): CWebApplication->run()
REQUEST_URI=/prestamo/prestamo/index.php?r=site/contact
in C:\xampp\htdocs\prestamo\prestamo\protected\controllers\SiteController.php (67)
in C:\xampp\htdocs\prestamo\prestamo\index.php (13)
2016/06/22 14:54:24 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "create".' in C:\xampp\htdocs\prestamo\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\prestamo\framework\web\CController.php(270): CController->missingAction('create')
#1 C:\xampp\htdocs\prestamo\framework\web\CWebApplication.php(282): CController->run('create')
#2 C:\xampp\htdocs\prestamo\framework\web\CWebApplication.php(141): CWebApplication->runController('site/create')
#3 C:\xampp\htdocs\prestamo\framework\base\CApplication.php(185): CWebApplication->processRequest()
#4 C:\xampp\htdocs\prestamo\prestamo\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/prestamo/prestamo/index.php?r=site/create
HTTP_REFERER=http://localhost:8080/prestamo/prestamo/index.php?r=site/index
---
2016/06/22 06:19:20 [error] [php] include(DbConnection.php): failed to open stream: No such file or directory (C:\xampp\htdocs\prestamo\framework\YiiBase.php:432)
Stack trace:
#0 unknown(0): spl_autoload_call()
#1 C:\xampp\htdocs\prestamo\framework\YiiBase.php(303): class_exists()
#2 C:\xampp\htdocs\prestamo\framework\YiiBase.php(196): import()
#3 C:\xampp\htdocs\prestamo\framework\base\CModule.php(393): createComponent()
#4 C:\xampp\htdocs\prestamo\framework\base\CApplication.php(459): CWebApplication->getComponent()
#5 C:\xampp\htdocs\prestamo\framework\db\ar\CActiveRecord.php(637): CWebApplication->getDb()
#6 C:\xampp\htdocs\prestamo\framework\db\ar\CActiveRecord.php(2386): Pago->getDbConnection()
#7 C:\xampp\htdocs\prestamo\framework\db\ar\CActiveRecord.php(411): CActiveRecordMetaData->__construct()
#8 C:\xampp\htdocs\prestamo\framework\db\ar\CActiveRecord.php(79): Pago->getMetaData()
#9 C:\xampp\htdocs\prestamo\prestamo\protected\controllers\PagoController.php(136): Pago->__construct()
#10 C:\xampp\htdocs\prestamo\framework\web\actions\CInlineAction.php(49): PagoController->actionAdmin()
#11 C:\xampp\htdocs\prestamo\framework\web\CController.php(308): CInlineAction->runWithParams()
#12 C:\xampp\htdocs\prestamo\framework\web\filters\CFilterChain.php(133): PagoController->runAction()
#13 C:\xampp\htdocs\prestamo\framework\web\filters\CFilter.php(40): CFilterChain->run()
#14 C:\xampp\htdocs\prestamo\framework\web\CController.php(1145): CAccessControlFilter->filter()
#15 C:\xampp\htdocs\prestamo\framework\web\filters\CInlineFilter.php(58): PagoController->filterAccessControl()
#16 C:\xampp\htdocs\prestamo\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter()
#17 C:\xampp\htdocs\prestamo\framework\web\CController.php(291): CFilterChain->run()
#18 C:\xampp\htdocs\prestamo\framework\web\CController.php(265): PagoController->runActionWithFilters()
#19 C:\xampp\htdocs\prestamo\framework\web\CWebApplication.php(282): PagoController->run()
#20 C:\xampp\htdocs\prestamo\framework\web\CWebApplication.php(141): CWebApplication->runController()
#21 C:\xampp\htdocs\prestamo\framework\base\CApplication.php(185): CWebApplication->processRequest()
#22 C:\xampp\htdocs\prestamo\prestamo\index.php(13): CWebApplication->run()
REQUEST_URI=/prestamo/prestamo/index.php?r=pago/admin
in C:\xampp\htdocs\prestamo\prestamo\protected\controllers\PagoController.php (136)
in C:\xampp\htdocs\prestamo\prestamo\index.php (13)
2016/06/22 06:34:50 [error] [system.db.CDbCommand] CDbCommand::() failed: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '='test1'ANDpassword='pass1'AND activo=1' at line 1. The SQL statement executed was: SELECT username,password FROM tbl_userWHERE username='test1'ANDpassword='pass1'AND activo=1.
in C:\xampp\htdocs\prestamo\prestamo\protected\components\UserIdentity.php (25)
in C:\xampp\htdocs\prestamo\prestamo\protected\models\LoginForm.php (52)
in C:\xampp\htdocs\prestamo\prestamo\protected\controllers\SiteController.php (94)
2016/06/22 06:34:51 [error] [exception.CDbException] exception 'CDbException' with message 'CDbCommand failed to execute the SQL statement: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '='test1'ANDpassword='pass1'AND activo=1' at line 1. The SQL statement executed was: SELECT username,password FROM tbl_userWHERE username='test1'ANDpassword='pass1'AND activo=1' in C:\xampp\htdocs\prestamo\framework\db\CDbCommand.php:543
Stack trace:
#0 C:\xampp\htdocs\prestamo\framework\db\CDbCommand.php(377): CDbCommand->queryInternal('', 0, Array)
#1 C:\xampp\htdocs\prestamo\prestamo\protected\components\UserIdentity.php(25): CDbCommand->query()
#2 C:\xampp\htdocs\prestamo\prestamo\protected\models\LoginForm.php(52): UserIdentity->authenticate()
#3 C:\xampp\htdocs\prestamo\framework\validators\CInlineValidator.php(42): LoginForm->authenticate('password', Array)
#4 C:\xampp\htdocs\prestamo\framework\validators\CValidator.php(201): CInlineValidator->validateAttribute(Object(LoginForm), 'password')
#5 C:\xampp\htdocs\prestamo\framework\base\CModel.php(159): CValidator->validate(Object(LoginForm), NULL)
#6 C:\xampp\htdocs\prestamo\prestamo\protected\controllers\SiteController.php(94): CModel->validate()
#7 C:\xampp\htdocs\prestamo\framework\web\actions\CInlineAction.php(49): SiteController->actionLogin()
#8 C:\xampp\htdocs\prestamo\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#9 C:\xampp\htdocs\prestamo\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#10 C:\xampp\htdocs\prestamo\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#11 C:\xampp\htdocs\prestamo\framework\web\CWebApplication.php(282): CController->run('login')
#12 C:\xampp\htdocs\prestamo\framework\web\CWebApplication.php(141): CWebApplication->runController('site/login')
#13 C:\xampp\htdocs\prestamo\framework\base\CApplication.php(185): CWebApplication->processRequest()
#14 C:\xampp\htdocs\prestamo\prestamo\index.php(13): CApplication->run()
#15 {main}
REQUEST_URI=/prestamo/prestamo/index.php?r=site/login
HTTP_REFERER=http://localhost:8080/prestamo/prestamo/index.php?r=site/login
---
2016/06/22 06:36:34 [error] [system.db.CDbCommand] CDbCommand::() failed: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '='test1'ANDpassword='pass1'AND activo=1' at line 1. The SQL statement executed was: SELECT username,password FROM tbl_userWHERE username='test1'ANDpassword='pass1'AND activo=1.
in C:\xampp\htdocs\prestamo\prestamo\protected\components\UserIdentity.php (25)
in C:\xampp\htdocs\prestamo\prestamo\protected\models\LoginForm.php (52)
in C:\xampp\htdocs\prestamo\prestamo\protected\controllers\SiteController.php (94)
2016/06/22 06:36:34 [error] [exception.CDbException] exception 'CDbException' with message 'CDbCommand failed to execute the SQL statement: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '='test1'ANDpassword='pass1'AND activo=1' at line 1. The SQL statement executed was: SELECT username,password FROM tbl_userWHERE username='test1'ANDpassword='pass1'AND activo=1' in C:\xampp\htdocs\prestamo\framework\db\CDbCommand.php:543
Stack trace:
#0 C:\xampp\htdocs\prestamo\framework\db\CDbCommand.php(377): CDbCommand->queryInternal('', 0, Array)
#1 C:\xampp\htdocs\prestamo\prestamo\protected\components\UserIdentity.php(25): CDbCommand->query()
#2 C:\xampp\htdocs\prestamo\prestamo\protected\models\LoginForm.php(52): UserIdentity->authenticate()
#3 C:\xampp\htdocs\prestamo\framework\validators\CInlineValidator.php(42): LoginForm->authenticate('password', Array)
#4 C:\xampp\htdocs\prestamo\framework\validators\CValidator.php(201): CInlineValidator->validateAttribute(Object(LoginForm), 'password')
#5 C:\xampp\htdocs\prestamo\framework\base\CModel.php(159): CValidator->validate(Object(LoginForm), NULL)
#6 C:\xampp\htdocs\prestamo\prestamo\protected\controllers\SiteController.php(94): CModel->validate()
#7 C:\xampp\htdocs\prestamo\framework\web\actions\CInlineAction.php(49): SiteController->actionLogin()
#8 C:\xampp\htdocs\prestamo\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#9 C:\xampp\htdocs\prestamo\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#10 C:\xampp\htdocs\prestamo\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#11 C:\xampp\htdocs\prestamo\framework\web\CWebApplication.php(282): CController->run('login')
#12 C:\xampp\htdocs\prestamo\framework\web\CWebApplication.php(141): CWebApplication->runController('site/login')
#13 C:\xampp\htdocs\prestamo\framework\base\CApplication.php(185): CWebApplication->processRequest()
#14 C:\xampp\htdocs\prestamo\prestamo\index.php(13): CApplication->run()
#15 {main}
REQUEST_URI=/prestamo/prestamo/index.php?r=site/login
HTTP_REFERER=http://localhost:8080/prestamo/prestamo/index.php?r=site/login
---
2016/06/22 06:38:00 [error] [system.db.CDbCommand] CDbCommand::() failed: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '='test1'ANDpassword='pass1'AND activo=1' at line 1. The SQL statement executed was: SELECT username,password FROM tbl_userWHERE username='test1'ANDpassword='pass1'AND activo=1.
in C:\xampp\htdocs\prestamo\prestamo\protected\components\UserIdentity.php (25)
in C:\xampp\htdocs\prestamo\prestamo\protected\models\LoginForm.php (52)
in C:\xampp\htdocs\prestamo\prestamo\protected\controllers\SiteController.php (94)
2016/06/22 06:38:00 [error] [exception.CDbException] exception 'CDbException' with message 'CDbCommand failed to execute the SQL statement: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '='test1'ANDpassword='pass1'AND activo=1' at line 1. The SQL statement executed was: SELECT username,password FROM tbl_userWHERE username='test1'ANDpassword='pass1'AND activo=1' in C:\xampp\htdocs\prestamo\framework\db\CDbCommand.php:543
Stack trace:
#0 C:\xampp\htdocs\prestamo\framework\db\CDbCommand.php(377): CDbCommand->queryInternal('', 0, Array)
#1 C:\xampp\htdocs\prestamo\prestamo\protected\components\UserIdentity.php(25): CDbCommand->query()
#2 C:\xampp\htdocs\prestamo\prestamo\protected\models\LoginForm.php(52): UserIdentity->authenticate()
#3 C:\xampp\htdocs\prestamo\framework\validators\CInlineValidator.php(42): LoginForm->authenticate('password', Array)
#4 C:\xampp\htdocs\prestamo\framework\validators\CValidator.php(201): CInlineValidator->validateAttribute(Object(LoginForm), 'password')
#5 C:\xampp\htdocs\prestamo\framework\base\CModel.php(159): CValidator->validate(Object(LoginForm), NULL)
#6 C:\xampp\htdocs\prestamo\prestamo\protected\controllers\SiteController.php(94): CModel->validate()
#7 C:\xampp\htdocs\prestamo\framework\web\actions\CInlineAction.php(49): SiteController->actionLogin()
#8 C:\xampp\htdocs\prestamo\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#9 C:\xampp\htdocs\prestamo\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#10 C:\xampp\htdocs\prestamo\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#11 C:\xampp\htdocs\prestamo\framework\web\CWebApplication.php(282): CController->run('login')
#12 C:\xampp\htdocs\prestamo\framework\web\CWebApplication.php(141): CWebApplication->runController('site/login')
#13 C:\xampp\htdocs\prestamo\framework\base\CApplication.php(185): CWebApplication->processRequest()
#14 C:\xampp\htdocs\prestamo\prestamo\index.php(13): CApplication->run()
#15 {main}
REQUEST_URI=/prestamo/prestamo/index.php?r=site/login
HTTP_REFERER=http://localhost:8080/prestamo/prestamo/index.php?r=site/login
---
2016/06/22 06:40:54 [error] [system.db.CDbCommand] CDbCommand::() failed: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '='test1'ANDpassword='pass1'AND activo=1' at line 1. The SQL statement executed was: SELECT username,password FROM tbl_userWHERE username='test1'ANDpassword='pass1'AND activo=1.
in C:\xampp\htdocs\prestamo\prestamo\protected\components\UserIdentity.php (25)
in C:\xampp\htdocs\prestamo\prestamo\protected\models\LoginForm.php (52)
in C:\xampp\htdocs\prestamo\prestamo\protected\controllers\SiteController.php (94)
2016/06/22 06:40:54 [error] [exception.CDbException] exception 'CDbException' with message 'CDbCommand failed to execute the SQL statement: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '='test1'ANDpassword='pass1'AND activo=1' at line 1. The SQL statement executed was: SELECT username,password FROM tbl_userWHERE username='test1'ANDpassword='pass1'AND activo=1' in C:\xampp\htdocs\prestamo\framework\db\CDbCommand.php:543
Stack trace:
#0 C:\xampp\htdocs\prestamo\framework\db\CDbCommand.php(377): CDbCommand->queryInternal('', 0, Array)
#1 C:\xampp\htdocs\prestamo\prestamo\protected\components\UserIdentity.php(25): CDbCommand->query()
#2 C:\xampp\htdocs\prestamo\prestamo\protected\models\LoginForm.php(52): UserIdentity->authenticate()
#3 C:\xampp\htdocs\prestamo\framework\validators\CInlineValidator.php(42): LoginForm->authenticate('password', Array)
#4 C:\xampp\htdocs\prestamo\framework\validators\CValidator.php(201): CInlineValidator->validateAttribute(Object(LoginForm), 'password')
#5 C:\xampp\htdocs\prestamo\framework\base\CModel.php(159): CValidator->validate(Object(LoginForm), NULL)
#6 C:\xampp\htdocs\prestamo\prestamo\protected\controllers\SiteController.php(94): CModel->validate()
#7 C:\xampp\htdocs\prestamo\framework\web\actions\CInlineAction.php(49): SiteController->actionLogin()
#8 C:\xampp\htdocs\prestamo\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#9 C:\xampp\htdocs\prestamo\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#10 C:\xampp\htdocs\prestamo\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#11 C:\xampp\htdocs\prestamo\framework\web\CWebApplication.php(282): CController->run('login')
#12 C:\xampp\htdocs\prestamo\framework\web\CWebApplication.php(141): CWebApplication->runController('site/login')
#13 C:\xampp\htdocs\prestamo\framework\base\CApplication.php(185): CWebApplication->processRequest()
#14 C:\xampp\htdocs\prestamo\prestamo\index.php(13): CApplication->run()
#15 {main}
REQUEST_URI=/prestamo/prestamo/index.php?r=site/login
HTTP_REFERER=http://localhost:8080/prestamo/prestamo/index.php?r=site/login
---
2016/06/22 06:42:49 [error] [system.db.CDbCommand] CDbCommand::() failed: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '='test1'ANDpassword='pass1'AND activo=1' at line 1. The SQL statement executed was: SELECT username,password FROM tbl_userWHERE username='test1'ANDpassword='pass1'AND activo=1.
in C:\xampp\htdocs\prestamo\prestamo\protected\components\UserIdentity.php (25)
in C:\xampp\htdocs\prestamo\prestamo\protected\models\LoginForm.php (52)
in C:\xampp\htdocs\prestamo\prestamo\protected\controllers\SiteController.php (94)
2016/06/22 06:42:49 [error] [exception.CDbException] exception 'CDbException' with message 'CDbCommand failed to execute the SQL statement: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '='test1'ANDpassword='pass1'AND activo=1' at line 1. The SQL statement executed was: SELECT username,password FROM tbl_userWHERE username='test1'ANDpassword='pass1'AND activo=1' in C:\xampp\htdocs\prestamo\framework\db\CDbCommand.php:543
Stack trace:
#0 C:\xampp\htdocs\prestamo\framework\db\CDbCommand.php(377): CDbCommand->queryInternal('', 0, Array)
#1 C:\xampp\htdocs\prestamo\prestamo\protected\components\UserIdentity.php(25): CDbCommand->query()
#2 C:\xampp\htdocs\prestamo\prestamo\protected\models\LoginForm.php(52): UserIdentity->authenticate()
#3 C:\xampp\htdocs\prestamo\framework\validators\CInlineValidator.php(42): LoginForm->authenticate('password', Array)
#4 C:\xampp\htdocs\prestamo\framework\validators\CValidator.php(201): CInlineValidator->validateAttribute(Object(LoginForm), 'password')
#5 C:\xampp\htdocs\prestamo\framework\base\CModel.php(159): CValidator->validate(Object(LoginForm), NULL)
#6 C:\xampp\htdocs\prestamo\prestamo\protected\controllers\SiteController.php(94): CModel->validate()
#7 C:\xampp\htdocs\prestamo\framework\web\actions\CInlineAction.php(49): SiteController->actionLogin()
#8 C:\xampp\htdocs\prestamo\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#9 C:\xampp\htdocs\prestamo\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#10 C:\xampp\htdocs\prestamo\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#11 C:\xampp\htdocs\prestamo\framework\web\CWebApplication.php(282): CController->run('login')
#12 C:\xampp\htdocs\prestamo\framework\web\CWebApplication.php(141): CWebApplication->runController('site/login')
#13 C:\xampp\htdocs\prestamo\framework\base\CApplication.php(185): CWebApplication->processRequest()
#14 C:\xampp\htdocs\prestamo\prestamo\index.php(13): CApplication->run()
#15 {main}
REQUEST_URI=/prestamo/prestamo/index.php?r=site/login
HTTP_REFERER=http://localhost:8080/prestamo/prestamo/index.php?r=site/login
---
2016/06/22 06:45:59 [error] [system.db.CDbCommand] CDbCommand::() failed: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '='test1'AND password='pass1' AND activo=1' at line 1. The SQL statement executed was: SELECT username,password FROM tbl_userWHERE username='test1'AND password='pass1' AND activo=1.
in C:\xampp\htdocs\prestamo\prestamo\protected\components\UserIdentity.php (25)
in C:\xampp\htdocs\prestamo\prestamo\protected\models\LoginForm.php (52)
in C:\xampp\htdocs\prestamo\prestamo\protected\controllers\SiteController.php (94)
2016/06/22 06:45:59 [error] [exception.CDbException] exception 'CDbException' with message 'CDbCommand failed to execute the SQL statement: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '='test1'AND password='pass1' AND activo=1' at line 1. The SQL statement executed was: SELECT username,password FROM tbl_userWHERE username='test1'AND password='pass1' AND activo=1' in C:\xampp\htdocs\prestamo\framework\db\CDbCommand.php:543
Stack trace:
#0 C:\xampp\htdocs\prestamo\framework\db\CDbCommand.php(377): CDbCommand->queryInternal('', 0, Array)
#1 C:\xampp\htdocs\prestamo\prestamo\protected\components\UserIdentity.php(25): CDbCommand->query()
#2 C:\xampp\htdocs\prestamo\prestamo\protected\models\LoginForm.php(52): UserIdentity->authenticate()
#3 C:\xampp\htdocs\prestamo\framework\validators\CInlineValidator.php(42): LoginForm->authenticate('password', Array)
#4 C:\xampp\htdocs\prestamo\framework\validators\CValidator.php(201): CInlineValidator->validateAttribute(Object(LoginForm), 'password')
#5 C:\xampp\htdocs\prestamo\framework\base\CModel.php(159): CValidator->validate(Object(LoginForm), NULL)
#6 C:\xampp\htdocs\prestamo\prestamo\protected\controllers\SiteController.php(94): CModel->validate()
#7 C:\xampp\htdocs\prestamo\framework\web\actions\CInlineAction.php(49): SiteController->actionLogin()
#8 C:\xampp\htdocs\prestamo\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#9 C:\xampp\htdocs\prestamo\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#10 C:\xampp\htdocs\prestamo\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#11 C:\xampp\htdocs\prestamo\framework\web\CWebApplication.php(282): CController->run('login')
#12 C:\xampp\htdocs\prestamo\framework\web\CWebApplication.php(141): CWebApplication->runController('site/login')
#13 C:\xampp\htdocs\prestamo\framework\base\CApplication.php(185): CWebApplication->processRequest()
#14 C:\xampp\htdocs\prestamo\prestamo\index.php(13): CApplication->run()
#15 {main}
REQUEST_URI=/prestamo/prestamo/index.php?r=site/login
HTTP_REFERER=http://localhost:8080/prestamo/prestamo/index.php?r=site/login
---
2016/06/22 06:46:33 [error] [system.db.CDbCommand] CDbCommand::() failed: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '='test1' AND password='pass1' AND activo=1' at line 1. The SQL statement executed was: SELECT username,password FROM tbl_userWHERE username='test1' AND password='pass1' AND activo=1.
in C:\xampp\htdocs\prestamo\prestamo\protected\components\UserIdentity.php (25)
in C:\xampp\htdocs\prestamo\prestamo\protected\models\LoginForm.php (52)
in C:\xampp\htdocs\prestamo\prestamo\protected\controllers\SiteController.php (94)
2016/06/22 06:46:33 [error] [exception.CDbException] exception 'CDbException' with message 'CDbCommand failed to execute the SQL statement: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '='test1' AND password='pass1' AND activo=1' at line 1. The SQL statement executed was: SELECT username,password FROM tbl_userWHERE username='test1' AND password='pass1' AND activo=1' in C:\xampp\htdocs\prestamo\framework\db\CDbCommand.php:543
Stack trace:
#0 C:\xampp\htdocs\prestamo\framework\db\CDbCommand.php(377): CDbCommand->queryInternal('', 0, Array)
#1 C:\xampp\htdocs\prestamo\prestamo\protected\components\UserIdentity.php(25): CDbCommand->query()
#2 C:\xampp\htdocs\prestamo\prestamo\protected\models\LoginForm.php(52): UserIdentity->authenticate()
#3 C:\xampp\htdocs\prestamo\framework\validators\CInlineValidator.php(42): LoginForm->authenticate('password', Array)
#4 C:\xampp\htdocs\prestamo\framework\validators\CValidator.php(201): CInlineValidator->validateAttribute(Object(LoginForm), 'password')
#5 C:\xampp\htdocs\prestamo\framework\base\CModel.php(159): CValidator->validate(Object(LoginForm), NULL)
#6 C:\xampp\htdocs\prestamo\prestamo\protected\controllers\SiteController.php(94): CModel->validate()
#7 C:\xampp\htdocs\prestamo\framework\web\actions\CInlineAction.php(49): SiteController->actionLogin()
#8 C:\xampp\htdocs\prestamo\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#9 C:\xampp\htdocs\prestamo\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#10 C:\xampp\htdocs\prestamo\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#11 C:\xampp\htdocs\prestamo\framework\web\CWebApplication.php(282): CController->run('login')
#12 C:\xampp\htdocs\prestamo\framework\web\CWebApplication.php(141): CWebApplication->runController('site/login')
#13 C:\xampp\htdocs\prestamo\framework\base\CApplication.php(185): CWebApplication->processRequest()
#14 C:\xampp\htdocs\prestamo\prestamo\index.php(13): CApplication->run()
#15 {main}
REQUEST_URI=/prestamo/prestamo/index.php?r=site/login
HTTP_REFERER=http://localhost:8080/prestamo/prestamo/index.php?r=site/login
---
2016/06/22 06:47:11 [error] [exception.CException] exception 'CException' with message 'Property "UserIdentity.errorcode" is not defined.' in C:\xampp\htdocs\prestamo\framework\base\CComponent.php:130
Stack trace:
#0 C:\xampp\htdocs\prestamo\prestamo\protected\components\UserIdentity.php(30): CComponent->__get('errorcode')
#1 C:\xampp\htdocs\prestamo\prestamo\protected\models\LoginForm.php(52): UserIdentity->authenticate()
#2 C:\xampp\htdocs\prestamo\framework\validators\CInlineValidator.php(42): LoginForm->authenticate('password', Array)
#3 C:\xampp\htdocs\prestamo\framework\validators\CValidator.php(201): CInlineValidator->validateAttribute(Object(LoginForm), 'password')
#4 C:\xampp\htdocs\prestamo\framework\base\CModel.php(159): CValidator->validate(Object(LoginForm), NULL)
#5 C:\xampp\htdocs\prestamo\prestamo\protected\controllers\SiteController.php(94): CModel->validate()
#6 C:\xampp\htdocs\prestamo\framework\web\actions\CInlineAction.php(49): SiteController->actionLogin()
#7 C:\xampp\htdocs\prestamo\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#8 C:\xampp\htdocs\prestamo\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#9 C:\xampp\htdocs\prestamo\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#10 C:\xampp\htdocs\prestamo\framework\web\CWebApplication.php(282): CController->run('login')
#11 C:\xampp\htdocs\prestamo\framework\web\CWebApplication.php(141): CWebApplication->runController('site/login')
#12 C:\xampp\htdocs\prestamo\framework\base\CApplication.php(185): CWebApplication->processRequest()
#13 C:\xampp\htdocs\prestamo\prestamo\index.php(13): CApplication->run()
#14 {main}
REQUEST_URI=/prestamo/prestamo/index.php?r=site/login
HTTP_REFERER=http://localhost:8080/prestamo/prestamo/index.php?r=site/login
---
2016/06/22 06:47:44 [error] [exception.CException] exception 'CException' with message 'Property "UserIdentity.errorcode" is not defined.' in C:\xampp\htdocs\prestamo\framework\base\CComponent.php:173
Stack trace:
#0 C:\xampp\htdocs\prestamo\prestamo\protected\components\UserIdentity.php(30): CComponent->__set('errorcode', 0)
#1 C:\xampp\htdocs\prestamo\prestamo\protected\models\LoginForm.php(52): UserIdentity->authenticate()
#2 C:\xampp\htdocs\prestamo\framework\validators\CInlineValidator.php(42): LoginForm->authenticate('password', Array)
#3 C:\xampp\htdocs\prestamo\framework\validators\CValidator.php(201): CInlineValidator->validateAttribute(Object(LoginForm), 'password')
#4 C:\xampp\htdocs\prestamo\framework\base\CModel.php(159): CValidator->validate(Object(LoginForm), NULL)
#5 C:\xampp\htdocs\prestamo\prestamo\protected\controllers\SiteController.php(94): CModel->validate()
#6 C:\xampp\htdocs\prestamo\framework\web\actions\CInlineAction.php(49): SiteController->actionLogin()
#7 C:\xampp\htdocs\prestamo\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#8 C:\xampp\htdocs\prestamo\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#9 C:\xampp\htdocs\prestamo\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#10 C:\xampp\htdocs\prestamo\framework\web\CWebApplication.php(282): CController->run('login')
#11 C:\xampp\htdocs\prestamo\framework\web\CWebApplication.php(141): CWebApplication->runController('site/login')
#12 C:\xampp\htdocs\prestamo\framework\base\CApplication.php(185): CWebApplication->processRequest()
#13 C:\xampp\htdocs\prestamo\prestamo\index.php(13): CApplication->run()
#14 {main}
REQUEST_URI=/prestamo/prestamo/index.php?r=site/login
HTTP_REFERER=http://localhost:8080/prestamo/prestamo/index.php?r=site/login
---
2016/06/22 06:47:56 [error] [exception.CException] exception 'CException' with message 'Property "UserIdentity.errorcode" is not defined.' in C:\xampp\htdocs\prestamo\framework\base\CComponent.php:173
Stack trace:
#0 C:\xampp\htdocs\prestamo\prestamo\protected\components\UserIdentity.php(30): CComponent->__set('errorcode', 0)
#1 C:\xampp\htdocs\prestamo\prestamo\protected\models\LoginForm.php(52): UserIdentity->authenticate()
#2 C:\xampp\htdocs\prestamo\framework\validators\CInlineValidator.php(42): LoginForm->authenticate('password', Array)
#3 C:\xampp\htdocs\prestamo\framework\validators\CValidator.php(201): CInlineValidator->validateAttribute(Object(LoginForm), 'password')
#4 C:\xampp\htdocs\prestamo\framework\base\CModel.php(159): CValidator->validate(Object(LoginForm), NULL)
#5 C:\xampp\htdocs\prestamo\prestamo\protected\controllers\SiteController.php(94): CModel->validate()
#6 C:\xampp\htdocs\prestamo\framework\web\actions\CInlineAction.php(49): SiteController->actionLogin()
#7 C:\xampp\htdocs\prestamo\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#8 C:\xampp\htdocs\prestamo\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#9 C:\xampp\htdocs\prestamo\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#10 C:\xampp\htdocs\prestamo\framework\web\CWebApplication.php(282): CController->run('login')
#11 C:\xampp\htdocs\prestamo\framework\web\CWebApplication.php(141): CWebApplication->runController('site/login')
#12 C:\xampp\htdocs\prestamo\framework\base\CApplication.php(185): CWebApplication->processRequest()
#13 C:\xampp\htdocs\prestamo\prestamo\index.php(13): CApplication->run()
#14 {main}
REQUEST_URI=/prestamo/prestamo/index.php?r=site/login
HTTP_REFERER=http://localhost:8080/prestamo/prestamo/index.php?r=site/login
---
2016/06/22 06:48:27 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'You are not authorized to perform this action.' in C:\xampp\htdocs\prestamo\framework\web\auth\CAccessControlFilter.php:182
Stack trace:
#0 C:\xampp\htdocs\prestamo\framework\web\auth\CAccessControlFilter.php(145): CAccessControlFilter->accessDenied(Object(CWebUser), 'You are not aut...')
#1 C:\xampp\htdocs\prestamo\framework\web\filters\CFilter.php(38): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 C:\xampp\htdocs\prestamo\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#3 C:\xampp\htdocs\prestamo\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#4 C:\xampp\htdocs\prestamo\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#5 C:\xampp\htdocs\prestamo\framework\web\CController.php(291): CFilterChain->run()
#6 C:\xampp\htdocs\prestamo\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 C:\xampp\htdocs\prestamo\framework\web\CWebApplication.php(282): CController->run('admin')
#8 C:\xampp\htdocs\prestamo\framework\web\CWebApplication.php(141): CWebApplication->runController('usuario/admin')
#9 C:\xampp\htdocs\prestamo\framework\base\CApplication.php(185): CWebApplication->processRequest()
#10 C:\xampp\htdocs\prestamo\prestamo\index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/prestamo/prestamo/index.php?r=usuario/admin
HTTP_REFERER=http://localhost:8080/prestamo/prestamo/index.php?r=site/login
---
2016/06/22 06:48:44 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'You are not authorized to perform this action.' in C:\xampp\htdocs\prestamo\framework\web\auth\CAccessControlFilter.php:182
Stack trace:
#0 C:\xampp\htdocs\prestamo\framework\web\auth\CAccessControlFilter.php(145): CAccessControlFilter->accessDenied(Object(CWebUser), 'You are not aut...')
#1 C:\xampp\htdocs\prestamo\framework\web\filters\CFilter.php(38): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 C:\xampp\htdocs\prestamo\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#3 C:\xampp\htdocs\prestamo\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#4 C:\xampp\htdocs\prestamo\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#5 C:\xampp\htdocs\prestamo\framework\web\CController.php(291): CFilterChain->run()
#6 C:\xampp\htdocs\prestamo\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 C:\xampp\htdocs\prestamo\framework\web\CWebApplication.php(282): CController->run('admin')
#8 C:\xampp\htdocs\prestamo\framework\web\CWebApplication.php(141): CWebApplication->runController('pago/admin')
#9 C:\xampp\htdocs\prestamo\framework\base\CApplication.php(185): CWebApplication->processRequest()
#10 C:\xampp\htdocs\prestamo\prestamo\index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/prestamo/prestamo/index.php?r=pago/admin
HTTP_REFERER=http://localhost:8080/prestamo/prestamo/index.php
---
